/**
 * Shared layout for ACHIEVER's static public pages (frontend/public/*.html).
 * Generated by scripts/build-public-pages.mjs — edit the sources in public-site/.
 */
export const SITE = {
  name: 'ACHIEVER',
  tagline: 'Save Together. Go Further.',
  origin: (process.env.PUBLIC_SITE_URL || process.env.VITE_PUBLIC_SITE_URL || '').replace(/\/$/, ''),
  supportEmail: process.env.VITE_SUPPORT_EMAIL || 'support@example.com',
  apiBase: (process.env.VITE_API_URL || '').replace(/\/$/, ''),
  updated: process.env.PUBLIC_PAGES_UPDATED || '23 September 2026',
};

export const NAV = [
  ['Documentation', '/documentation.html'],
  ['Security', '/security.html'],
  ['Support', '/support.html'],
  ['About', '/about.html'],
  ['Contact', '/contact.html'],
];

export const FOOTER = [
  ['Documentation', '/documentation.html'],
  ['Terms', '/terms.html'],
  ['Privacy', '/privacy.html'],
  ['Refund Policy', '/refund-policy.html'],
  ['Cookie Policy', '/cookie-policy.html'],
  ['Security', '/security.html'],
  ['Support', '/support.html'],
  ['Delete Data', '/delete-data.html'],
  ['Accessibility', '/accessibility.html'],
  ['Contact', '/contact.html'],
];

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Reviewed-by-counsel notice shown on every policy page. */
export const LEGAL_NOTICE = `<aside class="notice" role="note"><strong>Important:</strong> This page explains how ACHIEVER works in plain language.
It is not legal advice and has not yet been reviewed by Nigerian legal and compliance professionals; it must be reviewed before public launch.
ACHIEVER is not a bank, is not licensed by the Central Bank of Nigeria as a deposit-taking institution, and money recorded in ACHIEVER is not covered by NDIC deposit insurance.</aside>`;

export function page({ slug, title, description, h1, lead, body, toc = null, wide = false, extraHead = '' }) {
  const url = `${SITE.origin}/${slug}`;
  const nav = NAV.map(([l, h]) => `<a href="${h}"${h === `/${slug}` ? ' aria-current="page"' : ''}>${l}</a>`).join('');
  const footer = FOOTER.map(([l, h]) => `<a href="${h}">${l}</a>`).join('');
  const tocHtml = toc
    ? `<nav class="toc" aria-label="On this page"><p class="toc-title">On this page</p><ol>${toc.map(([id, label]) => `<li><a href="#${id}">${esc(label)}</a></li>`).join('')}</ol></nav>`
    : '';
  return `<!doctype html>
<html lang="en-NG">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} · ACHIEVER</title>
<meta name="description" content="${esc(description)}">
${SITE.origin ? `<link rel="canonical" href="${esc(url)}">` : ''}
<meta name="theme-color" content="#0B2A5B">
<meta property="og:site_name" content="ACHIEVER">
<meta property="og:title" content="${esc(title)} · ACHIEVER">
<meta property="og:description" content="${esc(description)}">
<meta property="og:type" content="website">
<meta property="og:image" content="${SITE.origin}/brand/og-image.png">
${SITE.origin ? `<meta property="og:url" content="${esc(url)}">` : ''}
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" type="image/png" sizes="32x32" href="/brand/favicon-32.png">
<link rel="apple-touch-icon" href="/brand/apple-touch-icon.png">
<link rel="stylesheet" href="/site/site.css">
<script>
  /* Same accessibility settings as the app (Settings → Accessibility), applied before paint. */
  try { var a = JSON.parse(localStorage.getItem('achiever.a11y') || '{}'), r = document.documentElement;
    if (a.fontScale) r.style.fontSize = Math.round(a.fontScale * 100) + '%';
    r.dataset.motion = a.reducedMotion || 'system'; r.dataset.contrast = a.highContrast ? 'high' : 'normal';
    r.dataset.links = a.underlineLinks ? 'underline' : 'normal'; r.dataset.focus = a.strongFocus ? 'strong' : 'normal';
    r.dataset.targets = a.largerTargets ? 'large' : 'normal'; } catch (e) {}
  window.ACHIEVER_API = ${JSON.stringify(SITE.apiBase)};
</script>
${extraHead}
</head>
<body>
<a class="skip-link" href="#main">Skip to main content</a>
<header class="site-header">
  <div class="wrap header-inner">
    <a class="logo" href="/" aria-label="ACHIEVER home">
      <picture><source srcset="/brand/achiever-logo-stacked.webp" type="image/webp"><img src="/brand/achiever-logo-stacked.png" width="112" height="80" alt="ACHIEVER"></picture>
    </a>
    <button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button>
    <nav id="site-nav" class="site-nav" aria-label="Main">
      ${nav}
      <span class="nav-auth">
        <a class="btn btn-ghost" href="/login">Log in</a>
        <a class="btn btn-primary" href="/register">Create account</a>
      </span>
    </nav>
  </div>
</header>
<main id="main" tabindex="-1">
  <div class="hero-band"><div class="wrap">
    <h1>${esc(h1 || title)}</h1>
    ${lead ? `<p class="lead">${lead}</p>` : ''}
  </div></div>
  <div class="wrap ${toc ? 'with-toc' : ''} ${wide ? 'wide' : ''}">
    ${tocHtml}
    <article class="content">${body}</article>
  </div>
</main>
<footer class="site-footer">
  <div class="wrap footer-inner">
    <div class="footer-brand">
      <img src="/brand/achiever-logo-stacked.png" width="104" height="75" alt="ACHIEVER">
      <p>${SITE.tagline}</p>
      <p class="small">ACHIEVER is not a bank and funds are not covered by deposit insurance.</p>
      <p class="small">© <span data-year>2026</span> ACHIEVER</p>
    </div>
    <nav class="footer-links" aria-label="Footer">${footer}</nav>
  </div>
</footer>
<script src="/site/site.js" defer></script>
</body>
</html>
`;
}
