import { Link } from 'react-router-dom';
import brand from '../../../public/brand/brand.json';

/**
 * The ONE place the ACHIEVER logo is rendered (official artwork supplied by the owner,
 * generated by scripts/brand-assets.mjs — never redrawn).
 *
 *   variant: full    – mark, wordmark and tagline
 *            stacked – mark and wordmark (headers)
 *            mark    – the "A" mark alone (tight spaces)
 *   tone:    auto    – follows light/dark theme (default)
 *            dark    – for a dark surface (white artwork) whatever the theme
 *            light   – for a light surface (ink artwork) whatever the theme
 * Sizes keep the artwork's own aspect ratio (object-fit: contain), so it is never stretched.
 */
const FILES = {
  full: { base: '/brand/achiever-logo-600', webp: true, ratio: brand.ratios.full },
  stacked: { base: '/brand/achiever-logo-stacked', webp: true, ratio: brand.ratios.stacked },
  mark: { base: '/brand/achiever-mark-192', webp: false, ratio: 1 },
};

function Picture({ file, dark, w, h, className }) {
  const suffix = dark ? '-dark' : '';
  return (
    <picture className={className}>
      {file.webp && <source srcSet={`${file.base}${suffix}.webp`} type="image/webp" />}
      <img src={`${file.base}${suffix}.png`} width={w} height={h} alt="ACHIEVER" decoding="async" className="brand-img" style={{ width: w, height: h }} />
    </picture>
  );
}

export function BrandImage({ variant = 'stacked', width, height, tone = 'auto', className = '' }) {
  const file = FILES[variant];
  const w = width ?? Math.round(height * file.ratio);
  const h = height ?? Math.round(width / file.ratio);
  if (tone !== 'auto') return <Picture file={file} dark={tone === 'dark'} w={w} h={h} className={className} />;
  // Both colourways are in the page; CSS shows the one that matches the theme (no flash, no JS).
  return (
    <span className={`brand-auto ${className}`}>
      <Picture file={file} dark={false} w={w} h={h} className="brand-on-light" />
      <Picture file={file} dark w={w} h={h} className="brand-on-dark" />
    </span>
  );
}

export default function BrandLogo({ variant = 'stacked', width, height, tone = 'auto', to = '/', label = 'ACHIEVER home', className = '' }) {
  const image = <BrandImage variant={variant} width={width} height={height} tone={tone} />;
  if (!to) return <span className={`brand-logo ${className}`}>{image}</span>;
  return (
    <Link to={to} className={`brand-logo ${className}`} aria-label={label}>
      {image}
    </Link>
  );
}

/** Same component under the name used in the design brief. */
export { BrandLogo as AchieverLogo };
